
ALTER TABLE "app_user" ALTER COLUMN role TYPE VARCHAR USING role::text;

ALTER TABLE "app_user" ALTER COLUMN status TYPE VARCHAR USING status::text;
ALTER TABLE "app_user" ALTER COLUMN status SET DEFAULT 'ACTIVE';

ALTER TABLE "teacher" ALTER COLUMN status TYPE VARCHAR USING status::text;
ALTER TABLE "teacher" ALTER COLUMN status SET DEFAULT 'ACTIVE';

ALTER TABLE "student" ALTER COLUMN status TYPE VARCHAR USING status::text;
ALTER TABLE "student" ALTER COLUMN status SET DEFAULT 'ACTIVE';

ALTER TABLE "group" ALTER COLUMN type TYPE VARCHAR USING type::text;

DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS status_enum;
DROP TYPE IF EXISTS group_type;